### ISSUE TITLE
証明書のエラーと「無効なURLです」

### ISSUE THREAD

**Issue by igrep** [e-bigmoon/haskell-blog#287]
所用により久々に https://haskell.e-bigmoon.com/ にアクセスしたところ証明書のエラー `NET::ERR_CERT_COMMON_NAME_INVALID` が発生し、無視して開くと次のメッセージが表示されました:

```
無効なURLです。
プログラム設定の反映待ちである可能性があります。
しばらく時間をおいて再度アクセスをお試しください。 
```

どうやら設定を間違えているようなので、確認・修正頂けないでしょうか？

**Comment by waddlaw** [comment]
@igrep ご連絡ありがとうございます。
(僕も別のとこで働いていたりなど) 色々あって現在は更新も停止している状態ということもあり、サイトでの公開は終了しました。すみません・・・。

コンテンツを非公開にするとアクセスできなくなっちゃうので今のまま放置していますが、更新できていないという理由で新たにホスティングする予定は今のところ考えていないです。

**Comment by igrep** [comment]
なるほど了解です。
